crm_api/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from django_filters.views import FilterView
from . import views
from . import filters
from crm_api.models import Customer, CustomerHistory


app_name = 'crm_api'
urlpatterns = [
    path('', views.CustomerList.as_view(), name='index'),
    path('create_client/', views.CustomerCreateView.as_view(), name='create_customer'),
    path('update_client/<int:pk>/', views.CustomerUpdate.as_view(), name='edit'),
    path('delete_client/<int:pk>/', views.CustomerDelete.as_view(), name='delete_customer'),
    path('search_customer/', FilterView.as_view(filterset_class=filters.CustomerFilter,
                                                template_name='crm_api/html/search_page.html'), name='select_customer'),
    path('result/', views.CustomerList.as_view(), name='customer_search_result'),
    path('list_files/<int:cust_id>/', views.CustomerFilesList.as_view(), name='list_files'),
    path('delete_file/<int:pk>/', views.CustomerFilesDelete.as_view(), name='delete_file'),
    path('download_file/<int:file_id>/', views.download_file, name='download_file'),
    path('create_folder/<int:cust_id>/', views.create_folder, name='create_folder'),
    re_path(r'^delete_folder/(?P<path>.*)/$', views.delete_folder, name='delete_folder'),
    path('edit_papers/<int:cust_id>/', views.edit_papers, name='edit_papers'),
    path('edit_wage/<int:cust_id>/', views.edit_wage, name='edit_wage'),
    path('edit_subwage/<int:cust_id>/', views.edit_sub_wage, name='edit_sub_wage'),
    path('edit_advance_tax/<int:cust_id>/', views.edit_advancetax, name='edit_advance_tax'),
    path('edit_withholding_tax/<int:cust_id>/', views.edit_withholding, name='edit_withholding_tax'),
    path('edit_tax_submit/<int:cust_id>/', views.edit_tax_submit, name='edit_tax_submit'),
    path('edit_road_tax_submit/<int:cust_id>/', views.edit_road_tax_submit, name='edit_road_tax_submit'),
    path('change_password/', views.change_password, name='change_password'),
    path('set_emails/', views.set_emails, name='set_emails'),
    path('create_email/', views.WarningEmailCreateView.as_view(), name='create_email'),
    path('edit_email/<int:pk>/', views.WarningEmailUpdate.as_view(), name='edit_email'),
    path('delete_email/<int:pk>/', views.WarningEmailDelete.as_view(), name='delete_email'),
    path('login/', auth_views.LoginView.as_view(template_name='crm_api/html/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
    path('archive/', views.CustomerHistoryView.as_view(), name='archive'),
]

crm_website/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('', include('crm_api.urls')),
    path('admin/', admin.site.urls),
]

crm_api/models.py
from django.db import models
from django.core.validators import RegexValidator

import datetime
import os


class Customer(models.Model):    
    CUSTOMER_LABELS = {
        'name': 'Název subjektu',
        'address': 'Adresa',
        'ico': 'IČO',
        'dic': 'DIČ',
        'email': 'Email',
        'tax_type': 'Právní subjekt',
        'tax_term': 'Termín podání přiznání - daň z příjmu',
        'vat': 'DPH',
        'tax_office': 'Finanční úřad',
        'soc_insurance': 'Sociální pojišťovna',
        'var_symbol': 'Variabilní symbol sociálního pojištění',
        'hea_insurance': 'Zdravotní pojišťovna',
        'phone': 'Telefon',
        'papers': 'Přinesl doklady k DPH',
        'wage': 'Mzdové podklady',
        'road_tax': 'Plátce silniční daně',
        'advance_tax': 'Zpracovaná zálohová daň',
        'withholding_tax': 'Zpracovaná srážková daň',
        'property_tax': 'Daň z nemovitosti',
        'moss': 'MOSS',
        'employer': 'Zaměstnavatel',
        'var_symbol_employees': 'Variabilní symbol zaměstnanci',
        'sub_tax': 'Podané přiznání DPH',
        'sub_road_tax': 'Podané přiznání silniční daně',
        'sub_wage': 'Zpracované mzdy',
    }
    CHOICES_VAT = [
        ('neplatce', 'Neplátce'),
        ('mesicne', 'Mesíčně'),
        ('ctvrtletne', 'Čtvrtletně')
    ]
    TAX_TYPES = [
        ('fo', 'Fyzická osoba'),
        ('po', 'Právnická osoba')
    ]
    TAX_TERMS = [
        ('radny', 'Řádný termín (1.4.)'),
        ('odlozeny', 'Odložený termín (1.7.)')
    ]
    PAPERS_TYPES = [
        (True, 'Přinesl'),
        (False, 'Nepřinesl'),
    ]

    name = models.CharField(max_length=100, verbose_name=CUSTOMER_LABELS['name'], 
                            validators=[RegexValidator(r'^\w(\w|\s|\.|,)*$',
                                                       'Povoleny jsou pouze znaky a-ž A-Ž 0-9 . , a mezera')])
    address = models.CharField(max_length=100, verbose_name=CUSTOMER_LABELS['address'])
    phone = models.CharField(max_length=20, blank=True, null=True, verbose_name=CUSTOMER_LABELS['phone'])
    ico = models.CharField(max_length=20, unique=True, blank=True, null=True, verbose_name=CUSTOMER_LABELS['ico'])
    dic = models.CharField(max_length=20, unique=True, blank=True, null=True, verbose_name=CUSTOMER_LABELS['dic'])
    email = models.EmailField(max_length=254, blank=True, null=True, verbose_name=CUSTOMER_LABELS['email'])
    tax_type = models.CharField(max_length=20, choices=TAX_TYPES, default='fo',
                                verbose_name=CUSTOMER_LABELS['tax_type'])
    tax_term = models.CharField(max_length=25, choices=TAX_TERMS, null=True, default='radny',
                                verbose_name=CUSTOMER_LABELS['tax_term'])
    vat = models.CharField(max_length=20, choices=CHOICES_VAT, default='neplatce',
                           verbose_name=CUSTOMER_LABELS['vat'])
    tax_office = models.CharField(max_length=254, blank=True, null=True, verbose_name=CUSTOMER_LABELS['tax_office'])
    soc_insurance = models.CharField(max_length=254, blank=True, null=True,
                                     verbose_name=CUSTOMER_LABELS['soc_insurance'])
    var_symbol = models.CharField(max_length=100, blank=True, null=True, verbose_name=CUSTOMER_LABELS['var_symbol'])
    hea_insurance = models.CharField(max_length=254, blank=True, null=True,
                                     verbose_name=CUSTOMER_LABELS['hea_insurance'])
    papers = models.BooleanField(null=True, blank=True, verbose_name=CUSTOMER_LABELS['papers'], choices=PAPERS_TYPES)
    wage = models.BooleanField(default=False, verbose_name=CUSTOMER_LABELS['wage'])
    advance_tax = models.BooleanField(default=False, verbose_name=CUSTOMER_LABELS['advance_tax'])
    withholding_tax = models.BooleanField(default=False, verbose_name=CUSTOMER_LABELS['withholding_tax'])
    property_tax = models.BooleanField(default=False, verbose_name=CUSTOMER_LABELS['property_tax'])
    road_tax = models.BooleanField(default=False, verbose_name=CUSTOMER_LABELS['road_tax'])
    moss = models.BooleanField(default=False, verbose_name=CUSTOMER_LABELS['moss'])
    is_employer = models.BooleanField(default=False, verbose_name=CUSTOMER_LABELS['employer'])
    var_symbol_employees = models.CharField(max_length=100, blank=True, null=True,
                                            verbose_name=CUSTOMER_LABELS['var_symbol_employees'])
    submitted_tax = models.BooleanField(default=False, verbose_name=CUSTOMER_LABELS['sub_tax'])
    submitted_road_tax = models.BooleanField(default=False, verbose_name=CUSTOMER_LABELS['sub_road_tax'])
    submitted_wage_tax = models.BooleanField(default=False, verbose_name=CUSTOMER_LABELS['sub_wage'])

    def __str__(self):
        return self.name


# FIND OUT HOW TO INHERIT AND SAVE IN ANOTHER DB_TABLE
class CustomerClone(models.Model):
    name = models.CharField(max_length=100,
                            validators=[RegexValidator(r'^\w(\w|\s|\.|,)*$',
                                                       'Povoleny jsou pouze znaky a-ž A-Ž 0-9 . , a mezera')])
    submitted_tax = models.BooleanField(default=False)
    submitted_road_tax = models.BooleanField(default=False)
    submitted_wage_tax = models.BooleanField(default=False)
    vat = models.CharField(max_length=20, default='neplatce')
    papers = models.BooleanField(null=True, blank=True)
    wage = models.BooleanField(default=False)
    advance_tax = models.BooleanField(default=False)
    withholding_tax = models.BooleanField(default=False)
    property_tax = models.BooleanField(default=False)
    road_tax = models.BooleanField(default=False)
    is_employer = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class CustomerFiles(models.Model):
    files = models.FileField()
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='files')
    file_path = models.CharField(max_length=255)

    def filename(self):
        return os.path.basename(self.files.name)

    def is_dir(self):
        return os.path.isdir(self.files.name)

    def __str__(self):
        return self.files.name


class CustomerHistory(models.Model):
    date = models.DateField(auto_now_add=True)
    customer = models.ForeignKey(to=CustomerClone, on_delete=models.CASCADE)


class WarningEmail(models.Model):
    DATE_NUMBERS = [
        (x, y) for x, y in zip([x for x in range(1, 29)], [str(y) for y in range(1, 29)])
    ]

    name = models.CharField(max_length=20, verbose_name='Název (interní)')
    subject = models.CharField(max_length=20, verbose_name='Předmět emailu')
    body = models.TextField(max_length=500, verbose_name='Tělo emailu')
    send_date = models.IntegerField(choices=DATE_NUMBERS, verbose_name='Číslo dne odeslání', unique=True)

    def __str__(self):
        return self.name

crm_api/forms.py
from django import forms
from .models import Customer, WarningEmail, CustomerFiles, CustomerHistory
from tempus_dominus.widgets import DatePicker

import datetime


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        exclude = ()
        labels = {
            'name': 'Název subjektu',
            'address': 'Adresa',
            'email': 'Email',
            'ico': 'IČO',
            'dic': 'DIČ',
            'hea_insurance': 'Zdravotní pojišťovna',
            'var_symbol': 'Variabilní symbol soc. poj.',
            'soc_insurance': 'Sociální pojišťovna',
            'vat': 'Plátce DPH',
            'tax_office': 'Finanční úřad',
            'phone': 'Telefon',
            'tax_type': 'Typ daně',
            'tax_term': 'Termín daně'
        }


class CustomerFilesForm:
    class Meta:
        model = CustomerFiles


class WarningEmailForm(forms.ModelForm):
    class Meta:
        model = WarningEmail
        exclude = ()
        label = {
            'name': 'Název',
            'subject': 'Předmět emailu',
            'body': 'Tělo emailu',
        }


class ArchiveForm(forms.Form):

    date_field = forms.DateField(label="",
                                 widget=DatePicker(attrs={'append': 'fa fa-calendar', 'icon_toggle': True}),
                                 initial=datetime.date.today().isoformat())

crm_api/templates/crm_api/html/_base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="cs">
<head>
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    {% bootstrap_css %}
    {% bootstrap_javascript jquery=1 %}
    {% bootstrap_messages %}
    {% block head %}
    {% endblock %}
    <style>
    body {
      min-height: 75rem;
      padding-top: 3.5rem;
    }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="{% url 'crm_api:index' %}"><i class="fa fa-home fa-fw" aria-hidden="true"></i>Hlavní stránka</a>
        <div class="collape navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                {% if perms.crm_api.add_customer %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'crm_api:create_customer' %}">
                            <i class="fa fa-plus fa-fw" aria-hidden="true"></i>Vytvořit nového klienta
                        </a>
                    </li>
                {% endif %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'crm_api:select_customer' %}">
                        <i class="fa fa-search fa-fw"></i>Vyhledávání s filtry
                    </a>
                </li>
                 <div class="dropdown">
                  <a href="#" class="nav-item active nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    <i class="fa fa-cog fa-fw" aria-hidden="true"></i>Nastavení
                  </a>
                  <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'crm_api:change_password' %}">Změnit heslo</a>
                    {% if perms.crm_api.change_warningemail %}
                        <a class="dropdown-item" href="{% url 'crm_api:set_emails' %}">Nastavení emailů</a>
                    {% endif %}
                  </div>
                </div>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'crm_api:archive' %}">
                        <i class="fa fa-history fa-fw" aria-hidden="true"></i>Historie
                    </a>
                </li>
                <form class="form-inline mt-2 mt-md-0" action="{% url 'crm_api:customer_search_result' %}" id="searchform" method="get" accept-charset="utf-8">
                <div class="form-group">
                    <input class="form-control mr-sm-2" id="searchbox" name="name" type="search" placeholder='Vyhledat klienta' required>
                </div>
                <button type="submit" class="btn btn-default"></button>
            </form>
            </ul>
        </div>
        <ul class="nav navbar-nav navbar-right">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'crm_api:logout' %}"><i class="fa fa-sign-out fa-fw"></i>Odhlásit se</a>
            </li>
        </ul>
    </nav>
    <div id="body-content">
        {% block body_content %}
        {% endblock body_content %}
    </div>
</body>
</html>

crm_api/templates/crm_api/html/_create.html
{% extends 'crm_api/html/_base.html' %}
{% load bootstrap4 %}
{% block body_content %}
{% if form %}
    <form style="display: inline" action="" method="post" enctype="multipart/form-data">
        {% block form_content %}
        {% endblock %}
        {% buttons submit='Uložit' %}{% endbuttons %}
    </form>
{% endif %}
    {% block content %}{% endblock %}
{% endblock %}

crm_api/templates/crm_api/html/_search.html
{% extends 'crm_api/html/_base.html' %}
{% load bootstrap4 %}
{% block body_content %}
    {% block search_content %}
    {% endblock %}
{% endblock %}

crm_api/templates/crm_api/html/_table_pagination.html
{% extends 'crm_api/html/_base.html' %}
{% load bootstrap4 %}
{% block body_content %}
    {% block body_extra %}
    {% endblock %}
    <table class="table table-bordered" >
        {% block table_head %}
        {% endblock %}
        {% block table_body %}
        {% endblock %}
    </table>
    {% bootstrap_pagination page_obj extra=request.GET.urlencode %}
    {% block extra_content %}{% endblock %}
{% endblock %}

crm_api/templates/crm_api/html/add_attachment.html
{% extends 'crm_api/html/_create.html' %}
{% block form_content %}
        <table style="color:black;text-align:left; margin-left: 20px;">
            {% csrf_token %}
            {{ form.as_table }}
        </table>
{% endblock %}

crm_api/templates/crm_api/html/change_password.html
{% extends "crm_api/html/_base.html" %}
{% load bootstrap4 %}
{% block body_content %}
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">Uložit</button>
        {% endbuttons %}
    </form>
{% endblock %}

crm_api/templates/crm_api/html/create_email.html
{% extends 'crm_api/html/_create.html' %}
{% load bootstrap4 %}
{% block form_content %}
    <table style="color:black;text-align:left; margin-left: 20px;">
        {% csrf_token %}
        {{ form.as_table }}
    </table>
{% endblock %}

crm_api/templates/crm_api/html/create_subject.html
{% extends 'crm_api/html/_create.html' %}
{% block head %}
    {% load static %}
    <script src="{% static 'customer_table.js' %}"></script>
{% endblock %}
{% block form_content %}
    <table style="color:black;text-align:left; margin-left: 20px;">
        {% csrf_token %}
        {{ form.as_table }}
    </table>
{% endblock %}

crm_api/templates/crm_api/html/file_list.html
{% extends 'crm_api/html/_base.html' %}
{% load bootstrap4 %}
{% block head %}
<style>
     /* The Modal (background) */
.modal {
    display: none; /* Hidden by default */
    position: fixed; /* Stay in place */
    z-index: 1; /* Sit on top */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /* Full height */
    overflow: auto; /* Enable scroll if needed */
    background-color: rgb(0,0,0); /* Fallback color */
    background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
}

/* Modal Content/Box */
.modal-content {
    background-color: #fefefe;
    margin: 15% auto; /* 15% from the top and centered */
    padding: 20px;
    border: 1px solid #888;
    width: 50%; /* Could be more or less, depending on screen size */
}

/* The Close Button */
.close {
    color: #aaa;
    float: right;
    font-size: 28px;
    font-weight: bold;
}

.close:hover,
.close:focus {
    color: black;
    text-decoration: none;
    cursor: pointer;
} 
.unstyled-button {
    border: none;
    background-color:  white;
}
</style>
{% endblock %}
{% block body_content %}
    {% buttons %}
    <button class="btn btn-primary" type="submit" id="file_button" name="new_file">
        Přidat soubor
    </button>
    <button class="btn btn-primary" type="submit" id="folder_button" name="new_folder">
        Nová složka
    </button>
    {% endbuttons %}
    <div id="file_list">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>
                        Název
                    </th>
                    <th>
                        Typ
                    </th>
                    <th>
                        Akce
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for file in files %}
                    <tr>
                    <td>
                        {% if file.isdir %}
                            <a href="?dir={% if dir_param %}{{ dir_param }}/{% endif %}{{ file.filename }}">{{ file.filename }}</a>
                        {% else %}
                            <a href="{% url 'crm_api:download_file' file_id=file.id %}" target="_blank">{{ file.filename }}</a>
                        {% endif %}
                    </td>
                    <td>
                        {% if file.isdir %}
                            Složka
                        {% else %}
                            Soubor
                        {% endif %}
                    </td>
                    <td>
                        <form method="POST" action="{% if not file.isdir %} {% url 'crm_api:delete_file' pk=file.id %} {% else %} {% url 'crm_api:delete_folder' path=file.media_path%} {% endif %}">
                            {% csrf_token %}
                            <button title="Smazat" type="submit" class="unstyled-button" onclick="return confirm('Opravdu chcete smazat {{ file.filename }}{% if file.isdir%} a vše, co je v této složce {% endif %}?')">
                                <i class="fa fa-trash"></i>
                            </button>
                        </form>
                    </td>
                    </tr>
                {% endfor %}
            </tbody>        
        </table>
    </div>
    <div id="create_file" class="modal-window modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <form action="" method="post" enctype="multipart/form-data">
                <table style="color:black;text-align:left; margin-left: 20px;">
                    {% csrf_token %}
                    {{ form.as_table }}
                </table>
                {% buttons submit='Uložit' %}{% endbuttons %}
            </form>
        </div>
    </div>
    <div id="create_folder" class="modal-window modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <form action="{% url 'crm_api:create_folder' cust_id %}?dir={{ dir_param }}" method="post">
                {% csrf_token %}
                <input type="text" maxlength="200" name="folder_name" placeholder="Název složky" required><br>
                <button class="btn btn-primary" type="submit">
                    Vytvořit
                </button>
            </form>
        </div>        
    </div>
    <script type="text/javascript">
        function setModals(modal, text, spanIdx)
        {
            var btn = document.getElementById(text + '_button');
            var span = document.getElementsByClassName("close")[spanIdx];
            btn.onclick = function() {
                modal.style.display = "block";
            }
            span.onclick = function() {
                modal.style.display = "none";
            }
        }
        var modal_file = document.getElementById('create_file');
        var modal_folder = document.getElementById('create_folder');
        setModals(modal_file, 'file', 0);
        setModals(modal_folder, 'folder', 1);
        window.onclick = function(event) {
            if (event.target == modal_file) {
                modal_file.style.display = "none";
            }
            else if (event.target == modal_folder) {
                modal_folder.style.display = "none";
            }
        }
</script>
{% endblock %}

crm_api/templates/crm_api/html/index.html
{% extends 'crm_api/html/_table_pagination.html' %}
{% load bootstrap4 %}
{% load date_extras %}
{% block head %}
{% if tax_pie_char or papers_pie_chart %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.bundle.min.js"></script>
{% endif %}
{% endblock %}
{% block table_head %}
<thead>
    <tr>
    <th>
        Název subjektu
    </th>
    <th>
        Mzdové podklady
    </th>
    <th>
        Mzdy
    </th>
    <th>
        Vyúčtování zálohové daně
    </th>
    <th>
        Vyúčtování srážkové daně
    </th>
    <th>
        Přinesl doklady DPH
    </th>
    <th>
        Přiznání DPH podáno
    </th>
    <th>
        Přiznání silniční daně podáno
    </th>
</tr>
</thead>
{% endblock %}
{% block table_body %}
<tbody>
    {% for customer in customer_list %}
        <tr>
            <td>
                {% if perms.crm_api.change_customer %}
                    <a href="{% url 'crm_api:edit' pk=customer.id %}">{{ customer.name }}</a>
                {% else %}
                    {{ customer.name }}
                {% endif %}
            </td>
            <td>
                {% if customer.is_employer %}
                    <a href="{% url 'crm_api:edit_wage' customer.id %}">
                    {% if customer.wage %}
                        <span class="fa fa-check">Přinesl</span>
                    {% else %}
                        <span class="fa fa-times">Nepřinesl</span>
                    {% endif %}
                    </a>
                    za {% last_month True %}
                    {% else %}
                        -
                {% endif %}
            </td>
            <td>
                {% if customer.is_employer %}
                <a href="{% url 'crm_api:edit_sub_wage' customer.id %}">
                {% if customer.submitted_wage_tax %}
                    <span class="fa fa-check">Zpracované</span>
                {% else %}
                    <span class="fa fa-times">Nezpracované</span>
                {% endif %}
                </a>
                 za {% last_month True %}
                {% else %}
                    -
                {% endif %}
            </td>
            <td>
                {% if customer.is_employer %}
                    <a href="{% url 'crm_api:edit_advance_tax' customer.id %}">
                    {% if customer.advance_tax %}
                        <span class="fa fa-check">Zpracované</span>
                    {% else %}
                        <span class="fa fa-times">Nezpracované</span>
                    {% endif %}
                    </a>
                    za rok {% last_year %}
                {% else %}
                    -
                {% endif %}
            </td>
            <td>
                {% if customer.is_employer %}
                    <a href="{% url 'crm_api:edit_withholding_tax' customer.id %}">
                    {% if customer.withholding_tax %}
                        <span class="fa fa-check">Zpracované</span>
                    {% else %}
                        <span class="fa fa-times">Nezpracované</span>
                    {% endif %}
                    </a>
                     za rok {% last_year %}
                {% else %}
                    -
                {% endif %}
            </td>
            <td>
                {% if customer.vat == "mesicne" or customer.vat == "ctvrtletne" %}
                {% buttons button_type="link" button_class="btn-primary" %}
                    <a href="{% url 'crm_api:edit_papers' customer.id %}">
                    {% if customer.papers %}
                        <span class="fa fa-check">Přinesl</span>
                    {% else %}
                        <span class="fa fa-times">Nepřinesl</span>
                    {% endif %}
                    </a>
                {% endbuttons %}
                {% else %}
                    -
                {% endif %}
            </td>
            <td>
                {% if customer.vat != 'neplatce' %}
                <a href="{% url 'crm_api:edit_tax_submit' customer.id %}">
                    {% if customer.submitted_tax %}
                        <span class="fa fa-check">Podáno</span>
                    {% else %}
                        <span class="fa fa-times">Nepodáno</span>
                    {% endif %}
                </a>
                    {% if customer.vat == 'mesicne' %}
                        k {% get_vat_deadline True %}
                    {% else %}
                        k {% get_vat_deadline False %}
                    {% endif %}
                {% else %}
                    Není plátce DPH
                {% endif %}
            </td>
            <td>
                {% if customer.road_tax %}
                    <a href="{% url 'crm_api:edit_road_tax_submit' customer.id %}">
                    {% if customer.submitted_road_tax %}
                        <span class="fa fa-check">Podáno</span>
                    {% else %}
                        <span class="fa fa-times">Nepodáno</span>
                    {% endif %}
                    </a>
                     za rok {% last_year %}
                {% else %}
                    -
                {% endif %}
            </td>
        </tr>
    {% endfor %}
</tbody>
{% endblock %}
{% block extra_content %}
{% if tax_pie_char or papers_pie_chart %}
<table style="width: 100%">
    <tbody>
        <tr>
            <td>
                {{ tax_pie_chart.as_html }}
            </td>
            <td>
                {{ papers_pie_chart.as_html }}
            </td>
        </tr>
    </tbody>
</table>
{% endif %}
{% endblock %}

crm_api/templates/crm_api/html/login.html
<!DOCTYPE html>
<html lang="en">
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery=1 %}
{% bootstrap_messages %}
<body>
    <div style="width:15%; margin-top: 10%" class="container center">
        <h1>Přihlášení</h1>
        <form action="" role="form" method="post">
            {% csrf_token %}
            {% bootstrap_field form.username layout='inline' %}
            {% bootstrap_field form.password layout='inline' %}
            {% buttons submit='Login' layout='inline' %}{% endbuttons %}
        </form>
    </div>
</body>
</html>

crm_api/templates/crm_api/html/search_page.html
{% extends "crm_api/html/_search.html" %}
{% load bootstrap4 %}
{% block search_content %}
    <form action="{% url 'crm_api:customer_search_result' %}" method="get" accept-charset="utf-8">
        <table style="color:black;text-align:left; margin-left: 20px;">
            {{ filter.form.as_table }}
        </table>
        {% buttons submit='Vyhledat' %}{% endbuttons %}
    </form>
{% endblock %}

crm_api/templates/crm_api/html/update_customer.html
{% extends 'crm_api/html/create_subject.html' %}
{% load bootstrap4 %}
{% load static %}
<script src="{% static 'customer_table.js' %}"></script>
{% block content %}
    <form method="POST" action="{% url "crm_api:delete_customer" pk=customer.id %}">
        {% csrf_token %}
        {% buttons %}
        <button class="btn btn-primary" type="submit" onclick="return confirm('Opravdu chcete smazat {{ customer.name }}?')">
            Smazat
        </button>
        {% endbuttons %}
    </form>
    <a class="btn btn-primary" href="{% url 'crm_api:list_files' cust_id=customer.id %}">Soubory klienta</a><br>
{% endblock %}